### ISSUE TITLE
platform specific?

### ISSUE THREAD

**Issue by gmaxferr** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#1]
Hello,
Quick Question: Is this plugin platform specific (Android only)? 
I'm asking since I really am needing a braintree plugin but for Android and iOS and this repo doesn't have "iOS" anywhere in the readme...

Thanks!

**Comment by deligence** [comment]
Hello,

Plugin is for Android as well as iOS. We haven't fully tested it with iOS, but it will work with iOS as well.

Regards,
Sanjay Kumar
https://www.deligence.com
