### ISSUE TITLE
DropIn "Select payment method " show only Paypal 

### ISSUE THREAD

**Issue by alevittoria** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#10]
Hello, I call the dropIn with this code but the only payment method showed is Paypal:

```dart

BraintreePayment braintreePayment = new BraintreePayment();
var data = await braintreePayment.showDropIn(nonce: ppToken,amount: currentValue.list_price.toStringAsFixed(1),inSandbox: true,enableGooglePay: true);
```

I have added inside Application in Manifest
```xml
<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>
```

But I'm not able to see Credit Card and Google Pay on dropIn.
Am I doing something wrong? 
Thanks.

**Comment by kadarsh11** [comment]
Hi @alevittoria ,

Have you pasted this activity inside your manifest.xml?

```xml
<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
        android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="com.example.htmlfun.braintree" />
            </intent-filter>
</activity>
```

**Comment by alevittoria** [comment]
Yes, I have done it.
The version of the library is 1.2.2
I'm thinking... Is it possible to disable some options like credit card payment by backend? Is it possible that it's the nonce that disables some options?

**Comment by alevittoria** [comment]
Ok, it's not a problem linked with the library, it is an option in Paypal account that disables credit cards payment, thanks for the help
