### ISSUE TITLE
Any way to remove credit card option in DropIn so PayPal is the only option?

### ISSUE THREAD

**Issue by garrettmortara** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#12]

**Comment by jameshp** [comment]
As far as I know, no there is no option to deactivate credit card and just have PayPal. Therefore the only option is to have the direct PayPal flow. I've implemented this in a fork for Android and ios, but not yet asked if we could merge this back to this package.

**Comment by deligence** [comment]
@jameshp - We'll be happy to merge your code in this repository. Please create a PR and we'll merge it.

**Comment by alevittoria** [comment]
Wait, I have the inverse problem, how it's possible? DropIn show me only Paypal. Is the version 1.2.2 the last one?
