### ISSUE TITLE
CocoaPods could not find compatible versions for pod "braintree_payment":

### ISSUE THREAD

**Issue by hkmsadek** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#14]
Hi, I am getting this error while using braintree_payment plugin in my ios project. I am using flutte r 1.10.7. 

Full error is 

```
CocoaPods could not find compatible versions for pod "braintree_payment":
      In Podfile:
        braintree_payment (from `.symlinks/plugins/braintree_payment/ios`)
    Specs satisfying the `braintree_payment (from `.symlinks/plugins/braintree_payment/ios`)` dependency were found, but they required a higher minimum deployment target.
.........
.........
........
Error running pod install
```

How can I solve this issue? Thank you.

**Comment by deligence** [comment]
Hi,

Please set your minimum deployment target higher than 10.0. 
You can find this setting inside Xcode in General tab.

<img width="600" height="450" alt="NTWfm" src="https://user-images.githubusercontent.com/8718725/67182070-f5577080-f3fb-11e9-8cf4-d686a56e7136.png">
