### ISSUE TITLE
Can I use this plugin on the ios side?

### ISSUE THREAD

**Issue by sinpobox** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#15]
I followed the guide to add this plugin to the project, but prompted the error ' Runner[65246:1178582] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method showDropIn on channel braintree_payment)' on ios

**Comment by hkmsadek** [comment]
I am also getting the same error :(

**Comment by hkmsadek** [comment]
Hi I solved it. There was googleEnabled as true. Just make it false and it will work :)
