### ISSUE TITLE
iOS PayPal additions

### ISSUE THREAD

**Issue by jameshp** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#2]
Hi, first of all, thx. for the great plugin. 

On iOS i had to follow the instructions  here https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4 
to be able to get the paypal flow working. 

Basic insturctions from braintree: 
1) Register URL Type
2) Update application delegate to setReturnUrlScheme
3) Update application delegate to pass the payment authorization URL to Braintree for finalization

Maybe this could be added to the description for iOS configuration?

**Comment by deligence** [comment]
Hi James,

Thanks for pointing it out. I have added it in the documentation.

**Comment by Dennis-Do** [comment]
Maybe someone can Help me with step 2 and 3. I am a Newbe to Apple Developement and don't understand the difference between...

> In your AppDelegate's...

and...

> Then in your application delegate...

... as it is described on the Braintree Page. I think the first part goes into Runner > Runner AppDelegate.swift (Yes i'm using the swift plugin) but where goes the second part?

Furthermore I get an error in AppDelegate.swift: Use of unresolved identifier 'BTAppSwitch'

Do I have to import something?

**Comment by Seanmclem** [comment]
> Maybe someone can Help me with step 2 and 3. I am a Newbe to Apple Development and don't understand the difference between...
> 
> > In your AppDelegate's...
> 
> and...
> 
> > Then in your application delegate...
> 
> ... as it is described on the Braintree Page. I think the first part goes into Runner > Runner AppDelegate.swift (Yes i'm using the swift template) but where goes the second part?
> 
> Furthermore I get an error in AppDelegate.swift: Use of unresolved identifier 'BTAppSwitch'
> 
> Do I have to import something?

Did you ever figure out `Use of unresolved identifier 'BTAppSwitch'` ?
