### ISSUE TITLE
Android app crash when press back button on the appbar in the card number entry screen

### ISSUE THREAD

**Issue by ronzoni-s** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#20]
Hi,
the problem occures when I am in the card number entry page and I press the back button in the appbar. Then, if I quickly press on the screen to dismiss the payment methods selection popup, the app crashes with the following errors.

![errors](https://user-images.githubusercontent.com/55026472/69357055-c21b3200-0c84-11ea-8346-3b55b6ccad08.png)

This behavior doesn't happen if I come back with the device back button, so it seems to be a backbutton problem from native code
I tried to found a solution but I couldn't.

Please, if someone could help me.

Thanks

**Comment by deligence** [comment]
The issue has been fixed in the latest version.
