### ISSUE TITLE
How to use custom ui for credit card

### ISSUE THREAD

**Issue by deepakrana0011** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#21]
I want to use my own custom ui for credit card and want to do payment with Braintree. How to achieve that ?

**Comment by jameshp** [comment]
The plugin uses, the drop-in ui, which you don't want to use.
Therefore braintree supports to use the braintree sdk
https://developers.braintreepayments.com/guides/credit-cards/overview

Looking on iOS and assuming you do the ui in flutter: you'd need to send
the cardnumber, expiry year  through the message channel to the plugin and
execute the method described here on the native side
https://developers.braintreepayments.com/guides/credit-cards/client-side/ios/v4
and
then return the nonce result back to the flutter side.

could be a nice extension for the plugin.
