### ISSUE TITLE
BraintreeBrowserSwitchActivity missing

### ISSUE THREAD

**Issue by him123** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#22]
When I press paypal button

I/flutter ( 7546): Response of the payment {message: BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/v2#browser-switch for the correct configuration, status: fail}

**Comment by him123** [comment]
I have already put 

  <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="${applicationId}.braintree" />
            </intent-filter>
        </activity>

in my AndroidManifest.xml

**Comment by peternagy1332** [comment]
Same issue here.

**Comment by him123** [comment]
@peternagy1332 I have resolved the issue by changing the package name in AndroidManifest.xml. Actually my package was including space, and as per rule in Braintree doc you cannot have an app name containing space.
