### ISSUE TITLE
App crash, when inserting card details

### ISSUE THREAD

**Issue by taranpreet100** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#23]
Hi Team,

The problem occurs when I am inserting card details on the card page then hit on  "ADD CARD". On that moment, application crashed and "Lost connection" message shows on debug console.

How to solve it..

**Comment by rishabh-deligence** [comment]
The plugin was incompatible with the new version of flutter. A temp fix has been made. Try again with the latest version of the plugin. Let me know if you still face the issue. #25
