### ISSUE TITLE
How to get CLIENT NONCE 

### ISSUE THREAD

**Issue by ravindrababuvidya** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#29]
Hi Braintee Team ,

I don't have server but how to i get client nonce and how use this plugin please help me.

**Comment by jameshp** [comment]
you will need a server to process a payment.
See https://developers.braintreepayments.com/start/overview#how-it-works about
the overal payment process flow.
Braintree provides some server API implementations in different languages,
so it should be easy to use for you. (here a link to the nodejs version
https://developers.braintreepayments.com/start/hello-server/node )
