### ISSUE TITLE
Client Nonce

### ISSUE THREAD

**Issue by Robouste** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#3]
What is the client nonce and how do I get it ?

I tried this but get an "fail" error.

```
braintreePayment
    .showDropIn(
        nonce: "848438074",
        amount: "4.99",
        enableGooglePay: true)
    .then((value) {
  var t = value;
});
```

**Comment by Robouste** [comment]
Ok got it.

[Generate a client token](https://developers.braintreepayments.com/start/hello-server/dotnet#generate-a-client-token)

**Comment by JayM96** [comment]
Didn't found how to generate a client nounce in the test account of braintree sandbox.
