### ISSUE TITLE
Google pay is not available

### ISSUE THREAD

**Issue by aacesh** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#35]
I did all the things as you explained . But i didnot get google pay in my dropIn . How can i add google pay in dropIn ?

**Comment by rishabh-deligence** [comment]
@aacesh 
Did you pass `enableGooglePay:true` and `googleMerchantId: <your google merchantId` in the showDropIn?

**Comment by deligence** [comment]
Reopen. If it still doesn't work.

**Comment by JanuszHain** [comment]
It doesn't work for me, I have added In AndroidManifest:
`<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>`

And that's how I try to call library: 

```
payNow() async {
  BraintreePayment braintreePayment = BraintreePayment();
  var data = await braintreePayment.showDropIn(
    nonce: clientNonce,
    amount: "10.0",
    enableGooglePay: true,
    nameRequired: true,
    googleMerchantId: '12345678901234567890',
  );
  print("Response of the payment $data");
  return false;
}
```

My device has Android 11, Google Pixel 3a
