### ISSUE TITLE
Drop-in Localization

### ISSUE THREAD

**Issue by samuelsarix** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#4]
How do you, if it is even implemented, change the language of the Drop-in UI ?

**Comment by jameshp** [comment]
on android its automatically changed according to the systems language. 
on iOS it works as well. However on iOS i had to add the language in the project settings (under Localizations)

**Comment by deligence** [comment]
Thanks James for answering the question of Samuel.
