### ISSUE TITLE
Tokenization Key or client token was invalid.

### ISSUE THREAD

**Issue by Dennis-Do** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#40]
Can you confirm the plugin is still working?

I implemented Braintree payment a while ago on both, web and with your plugin. Both was working on my tests. Web is still working but in my app i get allways the message: 

"Tokenization Key or client token was invalid."

I don't do anything special:

`Future<PaymentResult> braintreePay(double amount) async {  
   String clientNonce;

    try {
      clientNonce = await _dataService.fetchBraintreeToken();
    } on Exception {
      return PaymentResult(credit: -1, valid: false);
    }

    BraintreePayment braintreePayment = new BraintreePayment();
    var data = await braintreePayment.showDropIn(
        nonce: clientNonce, amount: amount.toString(), enableGooglePay: false);
    //data contains the error message...
  }`

The clientNonce comes from a .NET Core Backend. As suggested before, nothing special here:

`
private void CreateGateway(ConfigData data)
        {
            Braintree.Environment environment;

            if (data.Environment == "SANDBOX")
                environment = Braintree.Environment.SANDBOX;
            else
                environment = Braintree.Environment.PRODUCTION;

            gateway = new BraintreeGateway()
            {
                Environment = environment,
                MerchantId = data.MerchantId,
                PublicKey = data.PublicKey,
                PrivateKey = data.PrivateKey
            };
        }

[HttpGet]
        public IActionResult GetToken(string customerId)
        {
            var clientToken = gateway.ClientToken.Generate();

            return Ok(clientToken);
        }`

I tested on sandbox only.

**Comment by deligence** [comment]
The plugin seems to be working. Will check why it's not working on your end and what's causing this issue.

**Comment by Dennis-Do** [comment]
Hello,

in the meantime i have found my mistake. .NET Core wraps my token in quotes. Ubelievable that i don't saw that earlier.

A simple text/plain and the error is gone:

`[HttpGet, Produces("text/plain")]
 public IActionResult GetToken(string customerId)
 {
     var clientToken = gateway.ClientToken.Generate();
     return Ok(clientToken);
 }`

Maybe it helps someone!
