### ISSUE TITLE
BraintreeBrowserSwitchActivity missing

### ISSUE THREAD

**Issue by Gursewak-Uppal** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#5]
Hi
I flowed all steps as mentions here but every time when i clicked on Paypal it shows the error 
" Response of the payment {message: BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml" even in manifest i already added BraintreeBrowserSwitchActivity and when i clicked on Credit or Debit card it's working.
Also GooglePay now showing even enableGooglePay is true.
Also it not working with FlutterFragmentActivity

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutter_app_braintree">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="flutter_app_braintree"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="${applicationId}.braintree" />
            </intent-filter>
        </activity>
        <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>

    </application>
</manifest>

import 'package:flutter/material.dart';
import 'package:braintree_payment/braintree_payment.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _nonce = 'sandbox_ktw687fv_*******************';
  final _controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[

              RaisedButton(
                child: Text('Pay'),
                onPressed: () => _pay(_controller.text),
              ),
              Text(_nonce),

            ],
          ),
        ),
      ),
    );
  }

  void _pay(String token) async {
    String clientNonce = _nonce;

    BraintreePayment braintreePayment = new BraintreePayment();
    var data = await braintreePayment.showDropIn(
        nonce: clientNonce, amount: "2.0", enableGooglePay: true);
    print("Response of the payment $data");
  }
}

**Comment by adarsh-deligence** [comment]
Hi,
```xml
<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
        android:launchMode="singleTask">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="${applicationId}.braintree" />
        </intent-filter>
    </activity
```
In above code you have to replace **${applicationId}** with your application ID. You can find you application ID inside android/app/build.gradle.

**Comment by Gursewak-Uppal** [comment]
@adarsh-deligence I already tried as you said, but my issue not solved

**Comment by deligence** [comment]
Could you show me the code of manifest.xml?

**Comment by Gursewak-Uppal** [comment]
@deligence already added in my issue , at the top

**Comment by deligence** [comment]
Paste the updated manifest.xml with your application ID added and the error stack trace to debug the issue.

**Comment by Gursewak-Uppal** [comment]
I/flutter (29148): Response of the payment {paymentNonce: tokencc_bh_zcqrk7_m843yq_nbjvxt_fmxyvs_ds7, message: BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/v2#browser-switch for the correct configuration, status: fail}

**Comment by Gursewak-Uppal** [comment]
Anyone there for my help?

**Comment by deligence** [comment]
What is your application ID of the app?

**Comment by Gursewak-Uppal** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
 package="**com.example.flutter_app_braintree**">

**Comment by Gursewak-Uppal** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
 package="com.example.flutter_app_braintree">

**Comment by deligence** [comment]
So have you pasted this inside your manifest.xml

```xml
<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
        android:launchMode="singleTask">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="com.example.flutter_app_braintree.braintree" />
        </intent-filter>
    </activity
```

**Comment by deligence** [comment]
Make sure you run

> flutter clean

then run your application using

> flutter run

**Comment by Gursewak-Uppal** [comment]
Tried as you told, but same issue again

**Comment by deligence** [comment]
I found the reason for this error. 

Braintree doesn't accept the underscore in the scheme parameter. 

So paste the below given code inside your manifest.xml. This time it will work.

```xml
<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
        android:launchMode="singleTask">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="com.example.flutterappbraintree.braintree" />
        </intent-filter>
    </activity
```

**Comment by Gursewak-Uppal** [comment]
Response

**Comment by deligence** [comment]
Are you using test client nonce or you are generating client nonce from the server?

**Comment by Gursewak-Uppal** [comment]
Test client nonce. 
sandbox_ktw687fv_fpgwsykbpjrvn*****

**Comment by aTeamSolace** [comment]
@Gursewak-Uppal @deligence https://github.com/DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter/issues/42
