### ISSUE TITLE
3DS

### ISSUE THREAD

**Issue by gillestasse** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#6]
Hello,

We are using your plugin for our application. It works beautifully. 
I was just wondering about the new 3D Secure.
Are there any changes we should do to the plugin ?
See : https://developers.braintreepayments.com/guides/3d-secure/client-side/javascript/v3

**Comment by deligence** [comment]
Hi,

Thanks for using our plugin.... we are glad that our plugin is working for you. Currently this plugin does not support 3D secure and also we don't have any plan to implement it in near future. 

If you want to contribute in this plugin...Please send us the pull request.

**Comment by florent-huran** [comment]
I'm currently working on my own for a bridge with 3D secure gestion.

I managed to handle it in iOS for now, I'm trying my best to finish both Android and iOS implementation by the end of the weekend.

Stay tuned @gillestasse

**Comment by gillestasse** [comment]
That´s great ! I will be able to test in both iOS and Android.

**Comment by florent-huran** [comment]
> That´s great ! I will be able to test in both iOS and Android.

See progression there: https://github.com/florent-huran/braintree_dropin I'll be committing all the weekend on it.

Currently iOS seems to work but I'll let you know when everything will be done and published
