### ISSUE TITLE
'braintree_payment/BraintreePaymentPlugin.h' file not found

### ISSUE THREAD

**Issue by Dennis-Do** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#7]
Hello,

i have problems to get this plugin running in Xcode. You can do the following simple steps to reproduce:

1. flutter create -i swift my_test_project
2. add 'braintree_payment: ^1.2.2' to pubspec.yaml
3. Open Runner.xcodeproj in ios folder
4. Set IOS Deployment Target to iOS 10.0
5. run 'pod install' in ios folder
6. Try to  build Runner.xcodeproj

<img width="869" alt="Bildschirmfoto 2019-09-01 um 15 01 34" src="https://user-images.githubusercontent.com/26918219/64076788-81390000-ccc9-11e9-8de7-c2810b3b2304.png">

**Comment by deligence** [comment]
Hi Dennis,

 I found out that, since you are creating a flutter project with swift template you are facing this issue....please use it with a ObjC template. 

This plugin is developed in ObjC and working of this plugin with a project in swift template is handled by flutter. 

You can read this thread for you issue
https://github.com/flutter/flutter/issues/25676

**Comment by Dennis-Do** [comment]
For me it is not possible to use ObjC template as some other plugins are written in Swift. The good news is that I get it to work.

This is what I have done:
1. Delete Podfile and Podfile.lock in ios folder
2. Run pods install in ios folder
3. Open Pods.xcodeproj in ios/Pods folder
4. Update all TARGETS (tab Build Settings) to the same Deployment Target and same Swift_Version

After that 

> flutter build ios

from command line is working and Archive from Product menu in Xcode too. Build from Xcode still gives me some errors but thats seems not to impact the build from command line.

Maybe that helps someone.

**Comment by deligence** [comment]
Glad to know that you make it work for your app and thanks for sharing the solution with everyone.
