### ISSUE TITLE
Request for including PayTM payment

### ISSUE THREAD

**Issue by JerinFrancisA** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#9]
It would help a lot of developers if the package lets us use Paytm payment. Kindly, consider including Paytm option. Thank you.

**Comment by kadarsh11** [comment]
Hi Jerin,

Braintree does not support PayTM as their payment methods. If you want to integrate Paytm payment in you app then please try this plugin https://pub.dev/packages/paytm.
